### PR TITLE
implement several standard words

### PR DESCRIPTION
**Pull request by lolbinarycat**
words added:
* SYNONYM
* [DEFINED]
* [UNDEFINED]
* BEGIN-STRUCTURE
* END-STRUCTURE
* +FIELD
* FIELD:
* CFIELD:
* FFIELD: (will only be defined if float support is enabled)

### CODE REVIEW

**Review by philburk — COMMENTED** [review]
Thanks for the contribution.
But this code fails to build in CI.
The words do not have stack diagrams.
And the new files do not have the required headers and license info.
Please submit an Issue with the new standard words that you would like to see added to pForth and I will add them.
I assume Forth 2012 is the standard we should be supporting.

**Comment by lolbinarycat** [comment]
is there some style guide that i should be following? i will add stack diagrams now, but i would have added them from the start if there was some guideline saying as much.

(the problem was that exists? is an immediate word)

**Comment by lolbinarycat** [comment]
everything has stack diagrams now, and should work properly.

**Comment by philburk** [comment]
I added these words based on the ANS definitions.
See #127 and #128

**Comment by philburk** [comment]
Thanks for suggesting these changes.

**Pull request closed without merging**
